server:
  port: 9091

spring:
  application:
    name: app-eggs

  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org.hibernate.SQL: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
  override-with-generic-response: false
